### ISSUE TITLE
trigger update on value change

### ISSUE THREAD

**Issue by bogdancss** [syropian/vue-input-autosize#4]
how can I update the width when changing the value of the input in another way than typing?

I have a v-model assigned to the input field - if I change the model, it does not update the width.

**Comment by syropian** [comment]
You need to bind to `:value`, not `v-model`. See here: https://github.com/syropian/vue-input-autosize#why-bind-to-value-instead-of-using-v-model

**Comment by bogdancss** [comment]
perfect - thank you.
